import './global.css';
import { GraphqlProvider } from './graphql-provider';
import { NextUIProvider } from '@nextui-org/react';
import { Header } from './header';

export const metadata = {
  title: 'Welcome to app-fe',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="m-2">
        <NextUIProvider>
          <GraphqlProvider>
            <Header />
            <main>{children}</main>
          </GraphqlProvider>
        </NextUIProvider>
      </body>
    </html>
  );
};

export default RootLayout;
