import './global.css';
import { GraphqlProvider } from './graphql-provider';
import { NextUIProvider } from '@nextui-org/react';
import { Header } from './header';
import { MultipleTabsCheck } from '../src/components';

export const metadata = {
  title: 'Welcome to app-fe',
  description: 'Generated by create-nx-workspace',
};

const PreventMultipleTabs = () => (
  <MultipleTabsCheck>
    <p>
      This application will not function reliably if multiple tabs are open.
    </p>
    <p>Close duplicate browser tabs and reload this page to continue</p>
  </MultipleTabsCheck>
);

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="m-2">
        <NextUIProvider>
          <GraphqlProvider>
            <PreventMultipleTabs />
            <Header />
            <main>{children}</main>
          </GraphqlProvider>
        </NextUIProvider>
      </body>
    </html>
  );
};

export default RootLayout;
