import './global.css';
import { GraphqlProvider } from './graphql-provider';

export const metadata = {
  title: 'Welcome to nx-next-nest',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <GraphqlProvider>{children}</GraphqlProvider>
      </body>
    </html>
  );
};

export default RootLayout;
